---
# tasks file for docker-registry

- name: login
  docker_login:
    #email: "nourelhouda.fdhila@esprit.tn"
    username: "nourfdhila123"
    password: "181jmt3049"
    reauthorize: yes
- name: docker push
  docker_image:
    name: appfront:latest
    repository: nourfdhila123/cdnour
    push: yes
    source: local 
